In [ ]:
import numpy as np

H = np.array([[1,2,3,1,2,3,4,7],
            [7,2,8,1,0,3,5,1],
            [1,1,3,5,3,0,4,2],
            [5,9,8,10,2,0,1,7],
            [1,7,3,1,7,3,4,10],
            [0,2,8,1,2,0,8,7],
            [7,4,7,1,6,3,1,0],
            [10,2,6,1,2,3,4,11]])

#H = np.array([[1,2],[3,4]])

print(H)

[[ 1  2  3  1  2  3  4  7]
 [ 7  2  8  1  0  3  5  1]
 [ 1  1  3  5  3  0  4  2]
 [ 5  9  8 10  2  0  1  7]
 [ 1  7  3  1  7  3  4 10]
 [ 0  2  8  1  2  0  8  7]
 [ 7  4  7  1  6  3  1  0]
 [10  2  6  1  2  3  4 11]]


In [ ]:
H = np.array([[1,2,3,4],[3,4,5,6],[0,7,8,1],[0,1,7,9]])

In [2]:
H_norm = H / np.linalg.norm(H)
print(H_norm)

[[0.02575985 0.05151971 0.07727956 0.02575985 0.05151971 0.07727956
  0.10303941 0.18031897]
 [0.18031897 0.05151971 0.20607882 0.02575985 0.         0.07727956
  0.12879926 0.02575985]
 [0.02575985 0.02575985 0.07727956 0.12879926 0.07727956 0.
  0.10303941 0.05151971]
 [0.12879926 0.23183867 0.20607882 0.25759853 0.05151971 0.
  0.02575985 0.18031897]
 [0.02575985 0.18031897 0.07727956 0.02575985 0.18031897 0.07727956
  0.10303941 0.25759853]
 [0.         0.05151971 0.20607882 0.02575985 0.05151971 0.
  0.20607882 0.18031897]
 [0.18031897 0.10303941 0.18031897 0.02575985 0.15455912 0.07727956
  0.02575985 0.        ]
 [0.25759853 0.05151971 0.15455912 0.02575985 0.05151971 0.07727956
  0.10303941 0.28335838]]


In [3]:
np.save("matrix", H_norm)